# Generated by Django 4.1.3 on 2023-01-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_alter_todolist_slno'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='Details',
            field=models.CharField(default='N/A', max_length=400),
        ),
    ]
