# Generated by Django 4.1.3 on 2023-01-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_todolist_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='Details',
        ),
    ]
